<?php return array (
  'october\\demo\\Plugin' => 'plugins/october/demo/Plugin.php',
  'deligencetechnologies\\dtworldclock\\Plugin' => 'plugins/deligencetechnologies/dtworldclock/Plugin.php',
  'martin\\quotes\\Plugin' => 'plugins/martin/quotes/Plugin.php',
  'mohsin\\carousel\\Plugin' => 'plugins/mohsin/carousel/Plugin.php',
  'thewizardplusplus\\microblog\\Plugin' => 'plugins/thewizardplusplus/microblog/Plugin.php',
  'pkleindienst\\blogsearch\\Plugin' => 'plugins/pkleindienst/blogsearch/Plugin.php',
  'octotco\\githubwidget\\Plugin' => 'plugins/octotco/githubwidget/Plugin.php',
  'romanov\\clearcachewidget\\Plugin' => 'plugins/romanov/clearcachewidget/Plugin.php',
  'rainlab\\blog\\Plugin' => 'plugins/rainlab/blog/Plugin.php',
  'rainlab\\builder\\Plugin' => 'plugins/rainlab/builder/Plugin.php',
  'indikator\\blogstat\\Plugin' => 'plugins/indikator/blogstat/Plugin.php',
  'offline\\sitesearch\\Plugin' => 'plugins/offline/sitesearch/Plugin.php',
  'system\\Controllers\\updates' => 'modules/system/controllers/updates.php',
  'backend\\Controllers\\index' => 'modules/backend/controllers/index.php',
  'Romanov\\ClearCacheWidget\\ReportWidgets\\ClearCache' => 'plugins/romanov/clearcachewidget/reportwidgets/ClearCache.php',
  'Thewizardplusplus\\Microblog\\LangUtils' => 'plugins/thewizardplusplus/microblog/LangUtils.php',
  'OFFLINE\\SiteSearch\\Components\\SiteSearchInclude' => 'plugins/offline/sitesearch/components/SiteSearchInclude.php',
);